import { StyleSheet } from "react-native";
import { RFPercentage, RFValue } from "react-native-responsive-fontsize";


const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#000",
        alignItems: 'center',
        justifyContent: 'center',
    },
    imageBackgroundMain: {
        flex: 1,
        width: 400,
        height:400,
    },
    tituloTema: {
        fontSize:RFValue(20),
        color: "#FFF",
        marginTop:20,
        marginBottom:30,
        marginLeft: 20,
    },
    imagePoster: {
        width: 150,
        height:250,
        marginRight: 20,
        resizeMode: "stretch",
    },
    containerPopulares: {
        marginLeft: 20,
        marginRight: 20,
    },
    blocoAzul: {
        width: 150,
        height: 100,
        backgroundColor: "#25465C", 
    },
    nomeAnime: {
        fontSize: 12,
        fontWeight: "bold",
        color: "#FFF",
        marginLeft: 5,
        marginTop:5,
        position: "absolute",
    },
    serie: {
        fontSize: 12,
        fontWeight: "bold",
        color: "#00A78F",
        marginLeft: 5,
        marginTop:70,
        position: "absolute",
    },
    miniCirculo: {
        fontSize: 15,
        fontWeight: "bold",
        color: "#FFF",
        marginLeft: 50,
        marginTop: 71,
        position: "absolute",
    },
    dublado: {
        fontSize: 12,
        fontWeight: "bold",
        color: "#FFF",
        marginLeft: 60,
        marginTop:70,
        position: "absolute",
    },
    miniCirculos: {
        fontSize: 15,
        fontWeight: "bold",
        color: "#FFF",
        marginLeft: 125,
        marginTop: 70,
        position: "absolute",
        flexDirection: "row",
    },
    textView: {
        position: 'absolute',
        marginTop: 250,
    },
    imageTextTitulo: {
        marginLeft: 10,
        fontSize: 25,
        color: "#FFF",
        fontWeight: 'bold',
    },
    imageTextDesc: {
        marginLeft: 10,
        fontSize: 12,
        color: "#FFF",
        fontWeight: 'bold',
    },
    btnEntrar: {  
        width: 200,
        height: 40,
        borderWidth:2,
        backgroundColor: "#FF6800",
        marginTop: 110,
        marginLeft: 5,
        position: "absolute",
    },
    textoBtn: {
        color: "#000",
        fontSize: 15,
        marginTop: 5,
        marginLeft: 45,
        fontWeight: "bold",
        textAlign: "center",
        position: "absolute",
    },
    seta: {
        resizeMode: "stretch",
        marginLeft:10,
        marginTop:5, 
        width: 25, 
        height:25, 
        position:"absolute",
    },
    blocoAzulBanner: {
        position:"absolute",
        width: 320,
        height: 180,
        marginLeft: 20,
        marginTop: 220,
        backgroundColor: "#25465C",
    },
    bannerImg: {
        resizeMode: "stretch",
        position:"absolute",
        width: 320,
        height: 220,
        marginLeft: 20,
        marginBottom: 300,
    },
    posterBanner: {
        resizeMode: "stretch", 
        position:"absolute",
        zIndex: 1,
        width: 150,
        height:220, 
        marginLeft: 30,
        marginTop: 165,
    },
    tituloBanner: {
        fontSize: 16,
        marginLeft: 180,
        marginTop: 10,
        color: "#FFF",
        fontWeight: "bold",
    },
    descBanner: {
        fontSize: 13,
        marginTop: 10,
        color: "#FFF",
        marginLeft: 170,
        textAlign:"justify",
    },
    serieBanner: {
        fontSize: 12,
        marginLeft: 170,
        marginTop: 25,
        color: "#00A78F",
        fontWeight: "bold",
    },
    miniCirculosBanner: {
        fontSize: 15,
        fontWeight: "bold",
        color: "#FFF",
        marginLeft: 290,
        marginTop: 150,
        position: "absolute",
        flexDirection: "row",
    },
    msgFim: {
        color: "#FFF",
        fontWeight: "bold",
        marginTop: 150,
        fontSize: 18,
        textAlign: "center",
        
    },
    btnVerTudo: {
        width: 200,
        height: 40,
        borderWidth:2,
        backgroundColor: "#FF6800",
        marginTop: 180,
        alignSelf: "center",
        position: "absolute",
    },
    btnPremium: {
        width: 320,
        height: 40,
        borderWidth:2,
        backgroundColor: "#F8C600",
        marginTop: 260,
        alignSelf: "center",
        position: "absolute",    
    },
    textoBtnPremium: {
        textAlign: "center",
        color: "#000",
        fontWeight: "bold",
        fontSize: 16,
        marginTop: 5,
    },
    textoBtnVerTudo: {
        textAlign: "center",
        color: "#000",
        fontWeight: "bold",
        fontSize: 20,
    },




});

export default styles